version: "3.9"

services:
  nginx:
    build: ".docker/local/nginx"
    container_name: pr-nginx
    ports:
      - "88:80"
    volumes:
      - ./public:/app/public
      - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: ".docker/local/php"
    container_name: pr-app
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "5173:5173"
    depends_on:
      - mysql

  mysql:
    build: ".docker/local/mysql"
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABSE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    container_name: pr-mysql